services:
  app:
    build:
      context: .devcontainer/
      dockerfile: Dockerfile
    entrypoint:
    - sleep
    - infinity
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
